version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: multivende
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: ./merchant
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

  merchant-frontend:
    build:
      context: ./merchant-frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./merchant-frontend:/app

volumes:
  postgres-data:
  prisma-data:
